name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: cargo update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-windows:
      name: Build on Windows
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: cargo update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-macos:
      name: Build on MacOS
      runs-on: macos-latest
      
      steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: cargo update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
